name : Build and deploy Web API to azure

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{steps.vars.outputs.short_sha}}

    steps:
      - name: Checkout Repository
        id: github
        uses: actions/checkout@v4

      - name: Setup WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Configure azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{vars.ACR_SERVER}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}

      - name: SHA from commit
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{github.sha}})" >> "$GITHUB_OUTPUT"
        
      - name: Build and push docker image to ACR
        env:
          ACR_REGISTRY: ${{vars.ACR_SERVER}}
          IMAGE_TAG: ${{steps.vars.outputs.short_sha}}
        run: |
          docker build -f Dockerfile \
           -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
           -t $ACR_REGISTRY/netapp:latest \
           .
          docker push $ACR_REGISTRY/netapp --all-tags

  deploy-app-to-aca:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: Login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy to ACA
        uses: azure/container-apps-deploy-action@v1
        with:
          registryUrl: ${{ vars.ACR_SERVER }}
          imageToDeploy: ${{ vars.ACR_SERVER }}/netapp:${{ needs.build-and-deploy.outputs.short_sha }}
          targetPort: 8080
          ingress: external
          containerAppName: nu-masternet-dev-eus-aca
          containerAppEnvironment: nu-masternet-dev-eus-acae
          resourceGroup: nu-masternet-dev-eus-rg
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=http://+:8080
            ConnectionStrings__SqlServerDatabase="${{ secrets.SQL_DB_CONNECTIONSTRING }}" 



  