name : Build and deploy Web API to azure

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        id: github
        uses: actions/checkout@v4

      - name: Setup WebApi .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Configure azure ACR
        uses: azure/docker-login@v2
        with:
          login-server: ${{ACR_SERVER}}
          username: ${{ACR_USERNAME}}
          password: ${{ACR_PASSWORD}}